amcl:
  ros__parameters:
    use_sim_time: false
    min_particles: 500
    max_particles: 2000
    transform_tolerance: 0.2
    recovery_alpha_slow: 0.001
    recovery_alpha_fast: 0.1
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    global_frame_id: "map"
    use_map_topic: true
    tf_broadcast: true
    laser_model_type: "likelihood_field"
    update_min_d: 0.2
    update_min_a: 0.2
    resample_interval: 1
    set_initial_pose: true
    scan_topic: "/scan"  # **Ensure AMCL listens to `/scan`**