ekf_filter_node:
  ros__parameters:
    frequency: 15.0
    two_d_mode: true

    # Frames
    map_frame: "map"
    odom_frame: "odom"
    base_link_frame: "base_link"

    # IMU (BNO055) - FIXED!
    imu0: "bno055/imu"
    imu0_config: [false, false, false,   # ❌ Do NOT estimate position
                  true, true, true,      # ✅ Use roll, pitch, yaw
                  false, false, false,   # ❌ No linear velocity
                  true, false, false,    # ✅ Use yaw velocity (angular Z)
                  true, true, false]     # ✅ Use X and Y acceleration!

    imu0_differential: false
    imu0_remove_gravitational_acceleration: true  

    process_noise_covariance: [
      0.001, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 
      0.0,  0.001, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  0.001, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 
      0.0,  0.0,  0.0,  0.01, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  
      0.0,  0.0,  0.0,  0.0,  0.01, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  
      0.0,  0.0,  0.0,  0.0,  0.0,  0.01, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.002, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.002, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.002, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.01, 0.0,  0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.01, 0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.02, 0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.01, 0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.01, 0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.015
    ]

    sensor_timeout: 1.0 
