slam_toolbox:
  ros__parameters:
    use_sim_time: false
    map_frame: "map"
    odom_frame: "odom"
    base_frame: "base_link"
    mode: "mapping"
    scan_topic: "/scan"
    resolution: 0.03
    max_laser_range: 5.5
    min_laser_range: 0.25
    publish_map: true
    publish_pose: true
    publish_tf: true
    transform_publish_period: 0.05
    map_update_interval: 0.5
    save_map_timeout: 5.0
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.05
    minimum_travel_heading: 0.05