slam_toolbox:
  ros__parameters:
    mode: "online_async"  # Change from 'mapping' to 'online_async' for continuous updates
    use_sim_time: false   # Make sure this is false unless using simulation
    map_update_interval: 0.2  # Update the map every 0.2 seconds
    resolution: 0.05      # Map resolution in meters (adjust as needed)
    max_laser_range: 8.0  # Set the max range of your LiDAR
    odom_frame: "odom"
    map_frame: "map"
    base_frame: "base_link"
    scan_topic: "/scan"   # Ensure this matches your LiDAR topic
    transform_timeout: 0.2
    mode: "online_async"
