ekf_filter_node:
  ros__parameters:
    frequency: 15.0
    two_d_mode: true

    # Frames
    map_frame: "map"
    odom_frame: "odom"
    base_link_frame: "base_link"

    imu0: "bno055/imu"
    imu0_config: [false, false, false,   
                  true, true, true,      
                  false, false, false,   
                  true, false, false,   
                  true, true, false]   

    imu0_differential: false
    imu0_remove_gravitational_acceleration: true  

    process_noise_covariance: [
      0.001, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 
      0.0,  0.001, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  0.001, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 
      0.0,  0.0,  0.0,  0.01, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  
      0.0,  0.0,  0.0,  0.0,  0.01, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  
      0.0,  0.0,  0.0,  0.0,  0.0,  0.01, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.002, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.002, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0, 
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.002, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.01, 0.0,  0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.01, 0.0,  0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.02, 0.0,  0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.01, 0.0,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.01, 0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.015
    ]

    sensor_timeout: 1.0 
