# slam_toolbox:
#   ros__parameters:
#     resolution: 0.05
#     map_frame: "map"
#     odom_frame: "odom"
#     base_frame: "base_link"
#     scan_topic: "/scan"
#     use_scan_matching: true  # ✅ Corrects position errors using scan matching
#     use_slam_backend: true   # ✅ Uses backend correction to fix drift
#     map_update_interval: 1.0
#     transform_publish_period: 0.05
#     minimum_travel_distance: 0.05  # ✅ Updates map even on small movements
slam_toolbox:
  ros__parameters:
    use_sim_time: false
    map_frame: "map"
    odom_frame: "odom"
    base_frame: "base_link"
    mode: "mapping"
    scan_topic: "/scan"
    resolution: 0.05
    max_laser_range: 6.0
    min_laser_range: 0.2
    map_start_x: -3.0
    map_start_y: -2.25
    map_size_x: 6.0
    map_size_y: 4.5
    publish_map: true
    publish_pose: true
    publish_tf: true
    transform_publish_period: 0.05
    map_update_interval: 2.0
    save_map_timeout: 5.0