# slam_toolbox:
#   ros__parameters:
#     resolution: 0.05
#     map_frame: "map"
#     odom_frame: "odom"
#     base_frame: "base_link"
#     scan_topic: "/scan"
#     use_scan_matching: true  # ✅ Corrects position errors using scan matching
#     use_slam_backend: true   # ✅ Uses backend correction to fix drift
#     map_update_interval: 1.0
#     transform_publish_period: 0.05
#     minimum_travel_distance: 0.05  # ✅ Updates map even on small movements

slam_toolbox:
  ros__parameters:
    use_sim_time: false
    map_frame: "map"
    odom_frame: "odom"
    base_frame: "base_link"
    mode: "mapping"  # Use "localization" if you load a saved map
    resolution: 0.05
    max_laser_range: 10.0
    publish_map: true
    publish_pose: true
    publish_tf: true