slam_toolbox:
  ros__parameters:
    resolution: 0.1   # Adjust resolution to fit your required size
    map_frame: "map"
    odom_frame: "odom"
    base_frame: "base_link"
    scan_topic: "/scan"
    max_laser_range: 6.0
    map_size_x: 1.5  # Total map width (meters)
    map_size_y: 0.9  # Total map height (meters)