planner_server:
  ros__parameters:
    use_sim_time: true
    expected_planner_frequency: 1.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_smac_planner/SmacPlanner2D"
      tolerance: 0.125
      downsample_costmap: false
      allow_unknown: false
      max_iterations: 1000000
      max_on_approach_iterations: 1000
      motion_model_for_search: "DUBIN" # or "REEDS_SHEPP", "DUBIN", "2D"
      angle_quantization_bins: 64
      analytic_expansion_ratio: 3.5
      minimum_turning_radius: 0.4 # adjust according to robot specs
